### ISSUE TITLE
Unsupported config option dockerfile

### ISSUE THREAD

**Issue by inelgnu** [youknowriad/zik42day#2]
docker-compose up -d throws an Unsupported config option for client service: 'dockerfile' error.

$docker-compose --version
docker-compose 1.2.0

why you do not simply use a standard Dockerfile ?

**Comment by youknowriad** [comment]
I use standard docker files and the standard docker-compose tool, I think you have to upgrade your docker-compose to 1.4.0

**Comment by inelgnu** [comment]
Sorry, i meant the **default** Dockerfile which work with the previous version of docker-compose.
=> client/docker/Dockerfile

Anyway if you want to keep this configuration, you should mention the requirements (docker-compose 1.4) in the README.

**Comment by youknowriad** [comment]
Ah ok, Thats because I'll add a prod docker file and a "prod" docker-compose to use in production without volumes.

**Comment by inelgnu** [comment]
i had the same issue, and i use to create a two separate folders : 
- dev/Dockerfile
- prod/Dockerfile

and multiple environnement dock-compose config files dev.yml/ prod.yml etc...

**Comment by youknowriad** [comment]
yes, nice solution as well but now that there's an option for the dockerfile, it's a little bit better I think
